### ISSUE TITLE
Live version of app is displaying the default text in index.html

### ISSUE THREAD

**Issue by matty22** [dalath/room-sprawl#62]
See the live version of the application here: 
https://rawgit.com/dalath/room-sprawl/master/index.html

For me it is showing 
"Room Title lol"
"A description of a room..."

**Comment by dalath** [comment]
Just a little error on line 42 ("addroom" should be "addRoom"). I changed it but it might take some time for the browser and/or rawgit to pick up on it.

**Comment by matty22** [comment]
Whoops, that was me. Sorry about that!
